---
title: "Data Processing Kalauhaihai"
author: "Connor"
date: "5/17/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(readr)
```


Reading in Data

```{r}
conductivity_kalauhaihai_garage_FebApr2023 <- read_csv(here("raw_data/kalauhaihai/data_conductivity_FebApr2023_KalauhaihaiGarage_21415543.csv"))
```


```{r}
conductivity_kalauhaihai_OctNov2022 <- read_tsv(here("raw_data/kalauhaihai/data_conductivity_Kalauhaihai_Oct-Nov2022.txt"))
```

```{r}
oxygen_kalauhaihai_garage_FebApr2023 <- read_csv(here("raw_data/kalauhaihai/Data_oxygen_FebApr2023_KalauhaihaiGarage_21446085.csv"))
```


removed an oxygen data set with the header

```{r}
oxygen_kalauhaihai_OctNov2022 <- read_tsv(here("raw_data/kalauhaihai/data_oxygen_Kalauhaihai_Oct-Nov2022.txt"))
```

```{r}
pH_kalauhaihai_garage_FebApr2023 <- read_csv(here("raw_data/kalauhaihai/data_pH_FebApr2023_KalauhaihaiGarage_20839036.csv"))
```

```{r}
pH_kalauhaihai_OctNov2022 <-
  read_tsv(here("raw_data/kalauhaihai/data_pH_Kalauhaihai_SN20839036_Oct-Nov2022.txt"))
```

```{r}
pH_kalauhaihai_Apr2022 <-
  read_tsv(here("raw_data/kalauhaihai/data_pH_Kalauhaihai_SN20839036_Apr2022.txt"), skip = 1)
```





```{r}
raw_temp_kalauhaihai_garage_Spring_2022 <- read.csv(here("raw_data/kalauhaihai/data_temp_Kalauhaihai_Garage_Spring_2022.csv"), header = TRUE)
```
sets the first line as a header, Im not sure if this is truly needed. HOWEVER, I imported with the name raw_temp because the format is really weird. 

```{r}
temp_kalauhaihai_garage_Spring_2022 <- raw_temp_kalauhaihai_garage_Spring_2022[seq(2, nrow(raw_temp_kalauhaihai_garage_Spring_2022), by = 2), ]
```
This code skips every EVEN line. In the raw data, there was an empty line between each 
element. 


Data Cleaning 

```{r}

# Clean Column Names


conductivity_kalauhaihai_garage_FebApr2023 <- conductivity_kalauhaihai_garage_FebApr2023 %>% 
  clean_names()


# Edit cleaned column names

colnames(conductivity_kalauhaihai_garage_FebApr2023)[which(names(conductivity_kalauhaihai_garage_FebApr2023) == "low_range_m_s_cm_lgr_s_n_21415543_sen_s_n_21415543")] <- "low_range_microSiemens"

colnames(conductivity_kalauhaihai_garage_FebApr2023)[which(names(conductivity_kalauhaihai_garage_FebApr2023) == "high_range_m_s_cm_lgr_s_n_21415543_sen_s_n_21415543")] <- "high_range_microSiemens"

colnames(conductivity_kalauhaihai_garage_FebApr2023)[which(names(conductivity_kalauhaihai_garage_FebApr2023) == "temp_c_lgr_s_n_21415543_sen_s_n_21415543")] <- "temp_celsius"

colnames(conductivity_kalauhaihai_garage_FebApr2023)[which(names(conductivity_kalauhaihai_garage_FebApr2023) == "date_time_gmt_10_00")] <- "date_time"


# Select relevant columns 

conductivity_kalauhaihai_garage_FebApr2023 <- conductivity_kalauhaihai_garage_FebApr2023 %>% 
  select(date_time, low_range_microSiemens, high_range_microSiemens, temp_celsius)
```

```{r}
temp_kalauhaihai_garage_Spring_2022 <- temp_kalauhaihai_garage_Spring_2022 %>% 
  clean_names()

colnames(temp_kalauhaihai_garage_Spring_2022)[which(names(temp_kalauhaihai_garage_Spring_2022) == "date_time_gmt_10_00")] <- "date_time"

colnames(temp_kalauhaihai_garage_Spring_2022)[which(names(temp_kalauhaihai_garage_Spring_2022) == "temp_c_lgr_s_n_20970094_sen_s_n_20970094")] <- "temp_celsius"

temp_kalauhaihai_garage_Spring_2022 <- temp_kalauhaihai_garage_Spring_2022 %>% 
  select(date_time, temp_celsius)

```

