---
title: "Hinas Graphs"
author: "Anson"
date: "2023-06-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(readr)
library(ggplot2)
library(plotly)
```

```{r}
ggplot(pH_kalauhaihai_OctNov2022, aes(date_time, pH)) +
  geom_line()
```

```{r}

```

```{r Conductivity Kanewai Spring}
conductivity_kanspring_trimmed <- conductivity_kanewai_spring_rock_feb_apr_2023 %>% 
  filter(date_time >= ymd("2023-02-10") & date_time <= ymd("2023-04-05"))
  
kanewai_spring_conductivity_plot <- ggplot(data = conductivity_kanspring_trimmed, aes(x = date_time, 
                                                      y = high_range_micro_siemens)) + 
  geom_line() +
  theme_minimal() +
  labs(title = "Kanewai Conductivity Spring",
       x = "Date & Time",
       y = "High range microSiemens (uS/cm)")
  

ggplotly(kanewai_spring_conductivity_plot)
```

```{r Conductivity Kalauhaihai Spring}
conductivity_kalspring_trimmed <- conductivity_kalauhaihai_garage_FebApr2023 %>% 
  filter(date_time >= ymd("2023-02-17") & date_time <= ymd("2023-04-05"))
  
kalauhaihai_spring_conductivity_plot <- ggplot(data = conductivity_kalspring_trimmed, aes(x = date_time, 
                                                      y = high_range_microSiemens)) + 
  geom_line() +
  theme_minimal() +
  labs(title = "Kalauhaihai Conductivity Spring",
       x = "Date & Time",
       y = "High range microSiemens (uS/cm)")
  

ggplotly(kalauhaihai_spring_conductivity_plot)
```

```{r Oxygen Kanewai Spring}
oxygen_kanspring_trimmed <- oxygen_kanewai_spring_rock_feb_apr_2023 %>% 
  filter(date_time >= ymd("2023-02-09") & date_time <= ymd("2023-04-05"))
  
kanewai_spring_oxygen_plot <- ggplot(data = oxygen_kanspring_trimmed, aes(x = date_time, 
                                                      y = dissolved_oxygen_mg_l)) + 
  geom_line() +
  theme_minimal() +
  labs(title = "Kanewai Dissolved Oxygen Spring",
       x = "Date & Time",
       y = "Dissolved Oxygen (mg/l)")
  

ggplotly(kanewai_spring_oxygen_plot)
```

```{r Oxygen Kalauhaihai Spring}
oxygen_kalspring_trimmed <- oxygen_kalauhaihai_garage_FebApr2023 %>% 
  filter(date_time >= ymd("2023-02-17") & date_time <= ymd("2023-04-05"))
  
kalauhaihai_spring_oxygen_plot <- ggplot(data = oxygen_kalspring_trimmed, aes(x = date_time, 
                                                      y = dissolved_oxygen_mg_l)) + 
  geom_line() +
  theme_minimal() +
  labs(title = "Kalauhaihai Dissolved Oxygen Spring",
       x = "Date & Time",
       y = "Dissolved Oxygen (mg/l)")
  

ggplotly(kalauhaihai_spring_oxygen_plot)
```





