---
title: "Data Processing Kanewai"
author: "Connor"
date: "5/17/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(readr)
```



#Reading in Data
As of May 25, 8 Data Files read in
  - 1 Conductivity
  - 1 Oxygen
  - 1 pH
  - 5 Temperature
  
```{r conductivity_kanewai_spring_rock_feb_apr_2023}
conductivity_kanewai_spring_rock_feb_apr_2023 <- read_csv(here("raw_data/kanewai/data_conductivity_FebApr2023_ KanewaiSpringRock_21415544.csv"))
```

```{r oxygen_kanewai_spring_rock_feb_apr_2023}
oxygen_kanewai_spring_rock_feb_apr_2023 <- read_csv(here("raw_data/kanewai/data_oxygen_FebApr2023_KanewaiSpringRock_21515403.csv"))
```

```{r pH_kanewai_spring_rock_feb_apr_2023}
pH_kanewai_spring_rock_feb_apr_2023 <- read_csv(here("raw_data/kanewai/data_pH_FebApr2023_KanewaiSpringRock_21433529.csv"))
```

```{r temp_kanewai_springledge_feb_apr_2023}
temp_kanewai_springledge_feb_apr_2023 <- read_csv(here("raw_data/kanewai/data_temp_FebApr2023_KanewaiSpringLedge_20970092.csv"))
```

```{r temp_kanewai_springledge_norfolk_feb_apr_2023}
temp_kanewai_springledge_norfolk_feb_apr_2023 <- read_csv(here("raw_data/kanewai/data_temp_FebApr2023_KanewaiFishpondLedgeEdgeNorfolk_20970108.csv"))
```

```{r temp_kanewai_xmasberry_feb_apr_2023}
temp_kanewai_xmasberry_feb_apr_2023 <- read_csv(here("raw_data/kanewai/data_temp_FebApr2023_KanewaiFishpondShadeUnderXmasBerry_21445019.csv"))
```

```{r temp_kanewai_spring_coconuttree_2022}
temp_kanewai_spring_coconuttree_2022 <- read_csv(here("raw_data/kanewai/data_temp_Kanewai_Cocunut_Tree_Spring_2022.csv"))
```

```{r temp_kanewai_spring_auwai_2022}
temp_kanewai_spring_auwai_2022 <- read_csv(here("raw_data/kanewai/data_temp_Kanewai_Auwai_Spring_2022.csv"))
```

#Data Cleaning 

```{r conductivity_kanewai_spring_rock_feb_apr_2023}
#Conductivity kanewai, spring rock, FEB_APR 2023

# Clean Column Names

conductivity_kanewai_spring_rock_feb_apr_2023 <- conductivity_kanewai_spring_rock_feb_apr_2023 %>% 
  clean_names()

# Edit cleaned column names

colnames(conductivity_kanewai_spring_rock_feb_apr_2023)[which(names(conductivity_kanewai_spring_rock_feb_apr_2023) == "high_range_m_s_cm_lgr_s_n_21415544_sen_s_n_21415544")] <- "high_range_microSiemens"

colnames(conductivity_kanewai_spring_rock_feb_apr_2023)[which(names(conductivity_kanewai_spring_rock_feb_apr_2023) == "temp_c_lgr_s_n_21415544_sen_s_n_21415544")] <- "temp_celsius"

colnames(conductivity_kanewai_spring_rock_feb_apr_2023)[which(names(conductivity_kanewai_spring_rock_feb_apr_2023) == "date_time_gmt_10_00")] <- "date_time"


# Select relevant columns 

conductivity_kanewai_spring_rock_feb_apr_2023 <- conductivity_kanewai_spring_rock_feb_apr_2023 %>% 
  select(date_time, high_range_micro_siemens, temp_celsius)

conductivity_kanewai_spring_rock_feb_apr_2023$date_time <- mdy_hms(conductivity_kanewai_spring_rock_feb_apr_2023$date_time)

```

```{r oxygen_kanewai_spring_rock_feb_apr_2023}
#Oxygen kanewai, spring rock, FEB_APR 2023

#Change column names

colnames(oxygen_kanewai_spring_rock_feb_apr_2023)[which(names(oxygen_kanewai_spring_rock_feb_apr_2023) == "DO conc, mg/L (LGR S/N: 21515403, SEN S/N: 21515403)")] <- "dissolved_oxygen_mg_l"

colnames(oxygen_kanewai_spring_rock_feb_apr_2023)[which(names(oxygen_kanewai_spring_rock_feb_apr_2023) == "Temp, °C (LGR S/N: 21515403, SEN S/N: 21515403)")] <- "temp_celsius"

colnames(oxygen_kanewai_spring_rock_feb_apr_2023)[which(names(oxygen_kanewai_spring_rock_feb_apr_2023) == "Date Time, GMT-10:00")] <- "date_time"

#Select Columns
oxygen_kanewai_spring_rock_feb_apr_2023 <- oxygen_kanewai_spring_rock_feb_apr_2023 %>%
  select(date_time, dissolved_oxygen_mg_l, temp_celsius)

oxygen_kanewai_spring_rock_feb_apr_2023$date_time <- mdy_hms(oxygen_kanewai_spring_rock_feb_apr_2023$date_time)

```

```{r pH_kanewai_spring_rock_feb_apr_2023}
#pH, kanewai, spring rock, FEB_APR 2023

#Change column names

colnames(pH_kanewai_spring_rock_feb_apr_2023)[which(names(pH_kanewai_spring_rock_feb_apr_2023) == "Ch: 3 - pH   (pH)")] <- "pH"

colnames(pH_kanewai_spring_rock_feb_apr_2023)[which(names(pH_kanewai_spring_rock_feb_apr_2023) == "Ch: 2 - Millivolts   (mv)")] <- "mv"

colnames(pH_kanewai_spring_rock_feb_apr_2023)[which(names(pH_kanewai_spring_rock_feb_apr_2023) == "Ch: 1 - Temperature   (°C)")] <- "temp_celsius"

colnames(pH_kanewai_spring_rock_feb_apr_2023)[which(names(pH_kanewai_spring_rock_feb_apr_2023) == "Date-Time (HST)")] <- "date_time"

#Select column names
pH_kanewai_spring_rock_feb_apr_2023 <- pH_kanewai_spring_rock_feb_apr_2023 %>%
  select(date_time, temp_celsius, mv, pH)

```

```{r temp_kanewai_spring_auwai_2022}
#temp, kanewai, spring auwai, 2022

#Change column names
colnames(temp_kanewai_spring_auwai_2022)[which(names(temp_kanewai_spring_auwai_2022) == "Date Time, GMT-10:00")] <- "date_time"

colnames(temp_kanewai_spring_auwai_2022)[which(names(temp_kanewai_spring_auwai_2022) == "Temp, °C (LGR S/N: 20970122, SEN S/N: 20970122)")] <- "temp_celsius"

#select columns
temp_kanewai_spring_auwai_2022 <- temp_kanewai_spring_auwai_2022 %>% 
  select(date_time, temp_celsius)

```

```{r temp_kanewai_spring_coconuttree_2022}
#temp, kanewai, spring auwai, 2022

#Change column names
colnames(temp_kanewai_spring_coconuttree_2022)[which(names(temp_kanewai_spring_coconuttree_2022) == "Date Time, GMT-10:00")] <- "date_time"

colnames(temp_kanewai_spring_coconuttree_2022)[which(names(temp_kanewai_spring_coconuttree_2022) == "Temp, °C (LGR S/N: 20970110, SEN S/N: 20970110)")] <- "temp_celsius"

#select columns
temp_kanewai_spring_coconuttree_2022 <- temp_kanewai_spring_coconuttree_2022 %>% 
  select(date_time, temp_celsius)

```

```{r temp_kanewai_springledge_feb_apr_2023}
#temp, kanewai, springledge, FEB_APR 2023

#Change column names
colnames(temp_kanewai_springledge_feb_apr_2023)[which(names(temp_kanewai_springledge_feb_apr_2023) == "Date Time, GMT-10:00")] <- "date_time"

colnames(temp_kanewai_springledge_feb_apr_2023)[which(names(temp_kanewai_springledge_feb_apr_2023) == "Temp, °C (LGR S/N: 20970092, SEN S/N: 20970092)")] <- "temp_celsius"

#select columns
temp_kanewai_springledge_feb_apr_2023 <- temp_kanewai_springledge_feb_apr_2023 %>% 
  select(date_time, temp_celsius)

```

```{r temp_kanewai_springledge_norfolk_feb_apr_2023}
#temp, kanewai, springledge norfolk, FEB_APR 2023

#Change column names
colnames(temp_kanewai_springledge_norfolk_feb_apr_2023)[which(names(temp_kanewai_springledge_norfolk_feb_apr_2023) == "Date Time, GMT-10:00")] <- "date_time"

colnames(temp_kanewai_springledge_norfolk_feb_apr_2023)[which(names(temp_kanewai_springledge_norfolk_feb_apr_2023) == "Temp, °C (LGR S/N: 20970108, SEN S/N: 20970108)")] <- "temp_celsius"

#select columns
temp_kanewai_springledge_norfolk_feb_apr_2023 <- temp_kanewai_springledge_norfolk_feb_apr_2023 %>% 
  select(date_time, temp_celsius)

```

```{r temp_kanewai_xmasberry_feb_apr_2023}
#temp, kanewai, xmasberry, FEB_APR 2023

#Change column names
colnames(temp_kanewai_xmasberry_feb_apr_2023)[which(names(temp_kanewai_xmasberry_feb_apr_2023) == "Date Time, GMT-10:00")] <- "date_time"

colnames(temp_kanewai_xmasberry_feb_apr_2023)[which(names(temp_kanewai_xmasberry_feb_apr_2023) == "Temp, °C (LGR S/N: 21445019, SEN S/N: 21445019)")] <- "temp_celsius"

#select columns
temp_kanewai_xmasberry_feb_apr_2023 <- temp_kanewai_xmasberry_feb_apr_2023 %>% 
  select(date_time, temp_celsius)

```